### ISSUE TITLE
Dotcom Figma v2 Epic

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom-design-kit#63]
### Epic to track Carbon for IBM.com Figma v2 

```[tasklist]
### Components
- [ ] Remove pages
- [ ] Overview
- [ ] Back to top
- [ ] Callout quote
- [ ] Callout with media
- [ ] Card default
- [ ] Card pictogram
- [ ] Card logo
- [ ] Card link
- [ ] Feature card
- [ ] Card group
- [ ] Card section
- [ ] Card section carousel
- [ ] Carousel
- [ ] Content block
- [ ] Content block cards
- [ ] Content block horizontal
- [ ] Content group
- [ ] Content group banner
- [ ] Content group cards
- [ ] Content group pictograms
- [ ] Content group simple
- [ ] Content item
- [ ] Content item horizontal
- [ ] Content section
- [ ] CTA
- [ ] CTA block & section
- [ ] Dotcom shell
- [ ] Expressive modal
- [ ] Feature section
- [ ] Filter panel
- [ ] Footer
- [ ] Horizontal rule
- [ ] Images
- [ ] Language selector
- [ ] Layout
- [ ] Lead space
- [ ] Lead space block
- [ ] Lead space search
- [ ] Leaving IBM modal
- [ ] Lightbox media viewer
- [ ] Link list
- [ ] Link list section
- [ ] Link with icon
- [ ] Locale modal
- [ ] Logo grid
- [ ] Masthead
- [ ] Pictogram item
- [ ] Quote
- [ ] Table of contents
- [ ] Tabs extended
- [ ] Tags
- [ ] Universal banner
- [ ] Video
```
